discoverer:
  host: "127.0.0.1"
  port: "9091"
  retry: 1
application:
  name: "simple-monitor"
  environment: "develop"
  log_file: "."
  log_level: "DEBUG"
parameter:
  version:
  group:
  retry: 0
  timeout: 3
  client_ip: "172.16.81.53"
reference:
  "php.dubbo.demo.DemoService":

